import { useState, useRef, useEffect, useCallback } from "react";
import { Header } from "./Components";
import { drawWheel } from "./utils";

export default function SpinScreen({ segments, mode, onResult, onReset }) {
  const [eliminated, setEliminated] = useState([]);
    const [spinning, setSpinning] = useState(false);
      const [rotation, setRotation] = useState(0);

        const canvasRef = useRef(null);
          const animRef = useRef(null);
            const rotRef = useRef(0);

              useEffect(() => {
                  drawWheel(canvasRef.current, segments, rotation, eliminated);
                    }, [segments, rotation, eliminated]);

                      const getActiveIndices = useCallback(() => {
                          return segments.map((_, i) => i).filter((i) => !eliminated.includes(i));
                            }, [segments, eliminated]);

                              const spin = () => {
                                  if (spinning) return;
                                      const active = getActiveIndices();
                                          if (active.length === 0) return;

                                              setSpinning(true);

                                                  const extraSpins = 5 + Math.random() * 5;
                                                      const targetAngle = extraSpins * 2 * Math.PI + Math.random() * 2 * Math.PI;
                                                          const duration = 3500 + Math.random() * 1000;
                                                              const start = performance.now();
                                                                  const startRot = rotRef.current;
                                                                      const ease = (t) => 1 - Math.pow(1 - t, 4);

                                                                          const animate = (now) => {
                                                                                const elapsed = now - start;
                                                                                      const t = Math.min(elapsed / duration, 1);
                                                                                            const current = startRot + targetAngle * ease(t);
                                                                                                  rotRef.current = current;
                                                                                                        setRotation(current);

                                                                                                              if (t < 1) {
                                                                                                                      animRef.current = requestAnimationFrame(animate);
                                                                                                                            } else {
                                                                                                                                    const arc = (2 * Math.PI) / active.length;
                                                                                                                                            const normalized = ((2 * Math.PI - (current % (2 * Math.PI))) + Math.PI / 2) % (2 * Math.PI);
                                                                                                                                                    const activeSlot = Math.floor(normalized / arc) % active.length;
                                                                                                                                                            const landed = active[activeSlot];
                                                                                                                                                                    setSpinning(false);

                                                                                                                                                                            if (mode === "pick") {
                                                                                                                                                                                      onResult(segments[landed]);
                                                                                                                                                                                              } else {
                                                                                                                                                                                                        const newElim = [...eliminated, landed];
                                                                                                                                                                                                                  setEliminated(newElim);
                                                                                                                                                                                                                            const remaining = active.filter((i) => i !== landed);
                                                                                                                                                                                                                                      if (remaining.length === 1) {
                                                                                                                                                                                                                                                  onResult(segments[remaining[0]]);
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                  animRef.current = requestAnimationFrame(animate);
                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                      const active = getActiveIndices();

                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                            <div style={{
                                                                                                                                                                                                                                                                                                  minHeight: "100vh",
                                                                                                                                                                                                                                                                                                        background: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
                                                                                                                                                                                                                                                                                                              display: "flex", flexDirection: "column", alignItems: "center", paddingBottom: 40,
                                                                                                                                                                                                                                                                                                                  }}>
                                                                                                                                                                                                                                                                                                                        <Header />
                                                                                                                                                                                                                                                                                                                              <div style={{ width: "100%", maxWidth: 480, padding: "0 16px", display: "flex", flexDirection: "column", alignItems: "center" }}>

                                                                                                                                                                                                                                                                                                                                      {/* Mode badge */}
                                                                                                                                                                                                                                                                                                                                              <div style={{
                                                                                                                                                                                                                                                                                                                                                        background: mode === "pick" ? "rgba(255,146,43,0.2)" : "rgba(255,107,107,0.2)",
                                                                                                                                                                                                                                                                                                                                                                  border: `1px solid ${mode === "pick" ? "rgba(255,146,43,0.4)" : "rgba(255,107,107,0.4)"}`,
                                                                                                                                                                                                                                                                                                                                                                            color: mode === "pick" ? "#FF922B" : "#FF6B6B",
                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 20, padding: "5px 16px",
                                                                                                                                                                                                                                                                                                                                                                                                fontFamily: "Nunito, sans-serif", fontWeight: 800, fontSize: 13,
                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                  }}>
                                                                                                                                                                                                                                                                                                                                                                                                                            {mode === "pick" ? "🏆 Pick a Winner" : `❌ Elimination · ${active.length} left`}
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Wheel + pointer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ position: "relative", width: "100%", maxWidth: 340 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          position: "absolute", top: -8, left: "50%", transform: "translateX(-50%)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: 0, height: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderLeft: "14px solid transparent",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRight: "14px solid transparent",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderTop: "30px solid #FFD93D",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      filter: "drop-shadow(0 2px 6px rgba(0,0,0,0.4))",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  zIndex: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <canvas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ref={canvasRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width={340}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          height={340}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{ width: "100%", borderRadius: "50%", boxShadow: "0 12px 40px rgba(0,0,0,0.5)", display: "block" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Spin button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={spin}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={spinning}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: 28, padding: "16px 48px", borderRadius: 50, border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: spinning ? "rgba(255,255,255,0.1)" : "linear-gradient(135deg, #FFD93D, #FF922B)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: spinning ? "rgba(255,255,255,0.4)" : "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontFamily: "Fredoka One, sans-serif", fontSize: 22,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cursor: spinning ? "default" : "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              boxShadow: spinning ? "none" : "0 8px 28px rgba(255,211,61,0.45)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          transition: "all 0.25s", letterSpacing: 0.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {spinning ? "Spinning... 🌀" : "SPIN! 🎰"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Eliminated list */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {eliminated.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ marginTop: 24, width: "100%" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ color: "rgba(255,255,255,0.45)", fontWeight: 800, fontSize: 11, textTransform: "uppercase", letterSpacing: 1, marginBottom: 8 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Eliminated
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {eliminated.map((i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={i} style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        display: "flex", alignItems: "center", gap: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: "rgba(255,255,255,0.04)", borderRadius: 10, padding: "8px 14px", marginBottom: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span style={{ fontSize: 20 }}>{segments[i].emoji}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span style={{ color: "rgba(255,255,255,0.4)", fontWeight: 700, fontSize: 14, textDecoration: "line-through" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {segments[i].name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={onReset} style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginTop: 20, background: "none", border: "1px solid rgba(255,255,255,0.15)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: "rgba(255,255,255,0.45)", borderRadius: 10, padding: "8px 20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontFamily: "Nunito, sans-serif", fontWeight: 700, fontSize: 13, cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ← Back to Setup
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                